all:
	g++ -g *.cpp -o main -lsfml-graphics -lsfml-window -lsfml-system

# all: main.o manager.o piece.o pieceSet.o
# 	g++ -g main.o manager.o piece.o pieceSet.o -o main -lsfml-graphics -lsfml-window -lsfml-system
	
# main.o:	main.cpp
# 	g++ -c main.cpp

# manager.o: manager.cpp
# 	g++ -c manager.cpp

# pieceSet.o: pieceSet.cpp 
# 	g++ -c pieceSet.cpp

# piece.o: piece.cpp
# 	g++ -c piece.cpp

# rook.o:	rook.cpp piece.h
# 	g++ -c rook.cpp piece.h
# link: 
# 	g++ -c main.cpp
# 	g++ main.o -o main -lsfml-graphics -lsfml-window -lsfml-system

clean:
	rm main
	rm *.o
	rm *.h.gch